# Generated by Django 3.2.9 on 2021-12-08 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flashcarddeck',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flashcarddeck',
            name='school_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard_app.school'),
        ),
    ]
