# Generated by Django 3.2.9 on 2021-12-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0002_auto_20211208_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcarddeck',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
