# Generated by Django 3.2.9 on 2021-12-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0003_alter_flashcarddeck_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='deck',
            new_name='flashcard_deck',
        ),
        migrations.RenameField(
            model_name='flashcarddeck',
            old_name='class_name',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='flashcarddeck',
            old_name='school_name',
            new_name='school',
        ),
    ]
