# Generated by Django 3.2.9 on 2021-12-09 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0005_auto_20211209_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcarddeck',
            name='author',
        ),
        migrations.RemoveField(
            model_name='flashcarddeck',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='flashcarddeck',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='flashcard_app.course'),
        ),
    ]
