# Generated by Django 3.2.9 on 2021-12-09 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0007_auto_20211209_2021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
