# Generated by Django 3.2.9 on 2021-12-09 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard_app', '0009_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcarddeck',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcard_app.course'),
        ),
    ]
